name: Terraform CI/CD

on:
  push:
    branches:
      - main  # Adjust branch name if necessary

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: latest

      # Set AWS credentials as environment variables
      - name: Configure AWS Credentials
        run: |
          echo "Configuring AWS credentials"
          echo "AWS_REGION=${{ secrets.AWS_REGION }}" >> $GITHUB_ENV
          echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> $GITHUB_ENV
          echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> $GITHUB_ENV

      # Terraform Init Step
      - name: Terraform Init
        run: |
          cd terraform/environment/development
          terraform init \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
            
      # Terraform Plan Step
    #  - name: Terraform Plan
     #   run: |
      #    cd terraform/environment/development
       #   terraform plan \
        #    -var="aws_region=${{ secrets.AWS_REGION }}" \
         #   -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          #  -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      # Terraform Apply Step
    #  - name: Terraform Apply
     #   run: |
      #    cd terraform/environment/development
       #   terraform apply -auto-approve \
        #    -var="aws_region=${{ secrets.AWS_REGION }}" \
         #   -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
          #  -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Destroy
        run: |
          cd terraform/environment/development
          terraform apply -auto-approve \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="aws_access_key=${{ secrets.AWS_ACCESS_KEY_ID }}" \
            -var="aws_secret_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}"
      
